### ISSUE TITLE
Error when shouting or posting

### ISSUE THREAD

**Issue by Zlecktov** [FroastJ/roblox-bots#12]
I have set this up properly and it worked for a while, but now it seems to be not working for some odd reason.   Every time I go to shout or post it does this:

The error it returns into console, because I print what it returns.

![http://prntscr.com/a7bdk0](http://i.imgur.com/nBZC22M.png)

**Comment by sentanos** [comment]
The first warning is due to your host. You can find fixes on the internet but it may be hard to do on your specific server. You can stop it from showing up by **removing** the line where it is set:

``` php
CURLOPT_FOLLOWLOCATION => true
```

In the case of the functions you referred to, it is not at all vital (everything runs absolutely fine without this line) and should not be causing the error following it.

The error with getAttribute typically occurs because of a number of reasons:
- The user is not logged in, typically because:
  - Incorrect credentials were used
  - The account's cookies expired
  - The account's password was changed or session logged out of, invalidating the cookie
- The account does not have permission to shout, typically because:
  - The account is not at a rank where they are allowed to shout in the group
  - The account is not 13+

The most common reason and the most probably reason in your case (considering you said it worked before) is that your cookies somehow got invalidated and the account is therefore not logged in. To fix this immediately, simply remove all cookie-related files. If you are using the default setup, these will be located in `/roblox-bots-master/Private/`. You can delete all files in this folder or only the files named `cookie` and `cookieTime`.

Depending on how this problem was caused in the first place, you may be able to fix it by lowering your login refresh time. If you are sure that the account wasn't changed between the time it was working and the time it stopped and the above fix worked, this is your best bet. 

The line that controls cookie refreshing in `receiver.php` is as follows:

``` php
if (time()-file_get_contents($cookieTime) > 86400) {
```

The key there is the number, it is the number of seconds that must pass between when it runs and the last login to login again. If you think the problem is related to the cookies not being refreshed enough, you can lower this number to 12 hours or 1 hour or 10 minutes (all in seconds), whatever works for you.

**Comment by Zlecktov** [comment]
Worked completely.  Thank you so much.

**Comment by Zlecktov** [comment]
The problem with the cookie is reoccurring.   It seems that whenever I check the CookieTIme the number is just a big random number.   I do not know what to do.  If you have any ideas please let me know.
