### ISSUE TITLE
Nothing works...

### ISSUE THREAD

**Issue by LukeTechnoUserOfficial** [FroastJ/roblox-bots#18]
I've updated my PHP and used the regular code. I've set it out correctly. When I use:

send('setRank',{2470023,13})
I get an internal server error

When I use:
send(game.Players.Froast,'setRank',{2470023,13})
I get "No Action"

It's all wrong!

**Comment by LukeTechnoUserOfficial** [comment]
I honestly need this to work as its really important to me...

**Comment by NNickey** [comment]
Do NOT post another issue again. You need to provide the full stack trace error, your current PHP version that FrostJ asked you to update to and actually attempt to fix the solution on your own as this error is entirely your responsibility!

You're not providing the 'internal server error' and the reason why you're receiving NoAction is because you formatted the way of sending an action wrong. You can't call an object when it expected a string..
