### ISSUE TITLE
Invalid Promotion Permissions Error

### ISSUE THREAD

**Issue by JohnWT** [FroastJ/roblox-bots#26]
I seem to be getting an error with **receiver.php** and **getRoles.php** while attempting to use changeRank.

I am consistently receiving the "Invalid promoting permissions" error while testing with Postman. I am positive that my login is correct, because the shout action works flawlessly. Yes, the bot has proper permissions to change ranks because it owns the group. Is there something obvious that I am overlooking? 

Here are the errors that are showing up in my error_log file:
`[06-Nov-2016 15:56:39 America/Denver] PHP Notice:  Undefined offset: 0 in receiver.php on line 39`
`[06-Nov-2016 15:56:40 America/Denver] PHP Warning:  Invalid argument supplied for foreach() in getRoles.php on line 11`

Pictures of the code for receiver.php and getRoles.php, my Postman setup, and my group setup follow below:

![receiver](https://cloud.githubusercontent.com/assets/23300772/20044614/3dacbb4c-a468-11e6-9315-c82d32d52d14.png)

![5dbb7a72fe6d110fb6cf6dee4a7c6b9f](https://cloud.githubusercontent.com/assets/23300772/20044621/4cf63b5a-a468-11e6-9e60-1e60a89d81f0.png)

![postman](https://cloud.githubusercontent.com/assets/23300772/20044622/52229c9a-a468-11e6-94a2-09085e3c88b6.png)

![07c210765c4b094cd673acba0f301244](https://cloud.githubusercontent.com/assets/23300772/20044659/9d1d0668-a468-11e6-9f8e-d6669bcf0926.png)

**Comment by sentanos** [comment]
This may be caused by 9e2c3cc, which I honestly did not have time to test. I have reverted this in 247fba0 to a version which I know is stable. Please download the repo again (specifically the [getRoles.php](https://github.com/sentanos/roblox-bots/blob/master/Includes/getRoles.php) file) and update your installation. Let me know if this fixes your issue.

The fact is this project is pretty dead, I will officially deprecate it soon but I'll say now that I encourage users to check out my [node bots](/sentanos/roblox-js-server) instead, which are up-to-date, maintained, and overall much more reliable.

**Comment by JohnWT** [comment]
Worked perfectly, thank you! I'll be sure to check out the node bots as well. Sorry for the late response.
